
<?php
    $userGuide = Mage::helper('storelocator')->__('
	Magento Store Locator extension allows locating stores and getting directions with Google Map integrated:<br />
        1. To add/ import stores with location, time schedule and other information, go to <strong>Store Locator</strong> -> <strong>Manage Stores</strong>.<br />
        2. To set days off for store(s), go to <strong>Store Locator</strong> -> <strong>Manage Holidays</strong>.<br />
        3. To set days with special working time for store(s), go to <strong>Store Locator</strong> -> <strong>Manage Special Days</strong>.<br />
        4. To configure Store Locator extension, go to <strong>Store Locator</strong> -> <strong>Settings</strong>.
    ');
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('storelocator')->__('General Instructions') ?></h4>        
    </div>
    <div class="fieldset ">
        <div class="hor-scroll">
            <?php echo $userGuide ?>
        </div>
    </div>
    
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('storelocator')->__('Instructions to create Google Map API Key') ?></h4>        
    </div>
    <div class="fieldset ">
        <div class="hor-scroll">
            <?php echo '1. Visit the APIs Console at'?> <a href="https://code.google.com/apis/console" target="_blank"><?php echo 'https://code.google.com/apis/console' ?></a><?php echo ' and log in with your Google Account.' ?>
            <br />
            <?php echo '2. Click on the <strong>APIs</strong> link in the left menu.' ?>
            <br />
            <?php echo '3. Activate the <strong>Google Maps JavaScript API v3</strong>, <strong>Distance Matrix API</strong>, <strong>Geocoding API</strong> services.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storelocator/guide/google-api-active.png' ?>" title="<?php echo $this->__('Google API Active') ?>" />
            <br />
            <br />
            <?php echo '4. Click on the <strong>Credentials</strong> link in the left menu,  the "CREATE NEW KEY" in the "Public API access" section to create Google Map API Key for browser apps.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storelocator/guide/create-key.png' ?>" title="<?php echo $this->__('Google API Active') ?>" />
        </div>
    </div>
    
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('storelocator')->__('Instructions to create Facebook API Key') ?></h4>        
    </div>
    <div class="fieldset ">
        <div class="hor-scroll">
             <?php echo '1. Visit the Facebook Developer page at '?> <a href="http://developers.facebook.com/setup/" target="_blank"><?php echo 'http://developers.facebook.com/setup/' ?></a><?php echo '  and log in with your Facebook Account.' ?>
              <br />
            <?php echo '2. Click on the <strong>Create New App</strong> button in the right.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storelocator/guide/create_new_appbutton.jpg' ?>" title="<?php echo $this->__('Create Facebook app') ?>" />
             <br />
            <?php echo '3. Fill in the form with required information to create a new Facebook app.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storelocator/guide/create_new_app_form.jpg' ?>" title="<?php echo $this->__('Create Facebook app') ?>" />
             <br />
            <?php echo '4. Click on the <strong>Settings</strong> link in the left menu.' ?>
             <br />
            <?php echo '5. Insert your domain into the App Domain field.' ?>
             <br />
            <?php echo '6. Copy the App ID and paste it in your back-end(Store Locator->Settings/Facebook API key).' ?>
             <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storelocator/guide/app_setting_form.jpg' ?>" title="<?php echo $this->__('Add domain') ?>" />
        </div>
    </div>
</div>